name: mgsim
channels:
  - conda-forge
  - r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.3
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.1
  - aws-c-io=0.15.2
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.4
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.6
  - aws-sdk-cpp=1.11.449
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - binutils_impl_linux-64=2.40
  - blosc=1.21.6
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2025.4.26
  - cairo=1.18.0
  - cfitsio=4.4.1
  - curl=8.10.1
  - expat=2.6.2
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - gcc_impl_linux-64=14.1.0
  - gdal=3.9.1
  - geos=3.12.2
  - geotiff=1.7.3
  - gfortran_impl_linux-64=14.1.0
  - giflib=5.2.2
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=14.1.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=75.1
  - json-c=0.17
  - kealib=1.5.3
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=15.1.0
  - libgcc-devel_linux-64=14.1.0
  - libgcc-ng=15.1.0
  - libgdal=3.9.1
  - libgdal-core=3.9.1
  - libgdal-fits=3.9.1
  - libgdal-grib=3.9.1
  - libgdal-hdf4=3.9.1
  - libgdal-hdf5=3.9.1
  - libgdal-jp2openjpeg=3.9.1
  - libgdal-kea=3.9.1
  - libgdal-netcdf=3.9.1
  - libgdal-pdf=3.9.1
  - libgdal-pg=3.9.1
  - libgdal-postgisraster=3.9.1
  - libgdal-tiledb=3.9.1
  - libgdal-xls=3.9.1
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=15.1.0
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsanitizer=14.1.0
  - libspatialite=5.1.0
  - libsqlite=3.49.2
  - libssh2=1.11.0
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=14.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzip=1.10.1
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.3
  - minizip=4.0.7
  - ncurses=6.5
  - nspr=4.35
  - nss=3.102
  - numpy=2.1.0
  - openjpeg=2.5.2
  - openssl=3.5.0
  - pango=1.54.0
  - pcre2=10.44
  - pip=24.2
  - pixman=0.43.2
  - poppler=24.07.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - proj=9.4.1
  - pthread-stubs=0.4
  - python=3.12.5
  - python_abi=3.12
  - r-base=4.4.1
  - r-rcpp=1.0.13
  - r-rcppparallel=5.1.9
  - r-terra=1.7_78
  - re2=2024.07.02
  - readline=8.2
  - s2n=1.5.9
  - sed=4.8
  - setuptools=72.2.0
  - snappy=1.2.1
  - spdlog=1.14.1
  - sqlite=3.49.2
  - sysroot_linux-64=2.17
  - tiledb=2.25.0
  - tk=8.6.13
  - tktable=2.10
  - tzcode=2024a
  - tzdata=2024a
  - uriparser=0.9.8
  - wheel=0.44.0
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.6
prefix: /glade/work/pilowskyj/conda-envs/mgsim
